version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "8003:80"
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/php
    depends_on:
      - php
  php:
    build:
      args:
        user: valmar
        uid: 1000
      dockerfile: ./.docker/php/Dockerfile
    working_dir: /var/www/php
    volumes:
      - ./:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./.docker/mysql/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10
